
server:
  port: 8088
spring:
  profiles:
    active: prod
  application:
    name: rabbit-music
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?chartacterEncoding=UTF-8&userSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}