server:
  port: ${APPLICATION_PORT}
spring:
  profiles:
    active: dev
  application:
    name: rabbit-music
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?chartacterEncoding=UTF-8&userSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
