#server:
#  port: 80
#spring:
#  profiles:
#    active: dev
#  application:
#    name: rabbit-music
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?chartacterEncoding=UTF-8&userSSL=false
#    username: ${MYSQL_USER_NAME}
#    password: ${MYSQL_PASSWORD}
#  datasource:
#    url: jdbc:mysql://47.103.199.19:3306/rabbit_music?chartacterEncoding=UTF-8&userSSL=false
#    username: root
#    password: 1234960
#    driver-class-name: com.mysql.cj.jdbc.Driver